export const userTypes = {
  SET_USER: "SET_USER",
  SET_TOKEN: "SET_TOKEN",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_DISCOVER_WEEKLY:"SET_DISCOVER_WEEKLY",
  SET_PLAYING: "SET_PLAYING",
  SET_ITEM: "SET_ITEM"
};
